#pragma once

// define all types of components
// will be updated in the order they are defined
enum COMPONENT_TYPE
{
	TRANSFORM_COMPONENT,
	MODEL_COMPONENT,
	TRANSFORMATION_COMPONENT,
	FREE_MOVE_COMPONENT,
	PING_PONG_COMPONENT,
	CAMERA_COMPONENT,
	QUAD_COMPONENT,
	DIR_LIGHT_COMPONENT,
	POINT_LIGHT_COMPONENT,
	UVSCROLL_COMPONENT,
	PARTICLE_COMPONENT,
	NUM_COMPONENT_TYPES
};
